sudo: required
services:
  - docker
before_install: 
  - docker build -t chrisvidal10/docker-react -f Dockerfile.dev .
script:
  - docker run chrisvidal10/docker-react npm run test -- --coverage
deploy:
  provider: heroku
  api_key:
    secure: KEY
  app: docker-react-course
  on:
    repo: chrisvidal10/docker-react