sudo: required
services:
  - docker

before_install: 
  - docker build -t chrisvidal10/docker-react -f Dockerfile.dev .

script:
  - docker run -it chrisvidal10/docker-react npm run tests -- --coverage